DROP TABLE purchase;
DROP TABLE buyer;
DROP TABLE product;

CREATE TABLE buyer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_buyer PRIMARY KEY (id)
);

CREATE TABLE product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   title VARCHAR(255),
   cost INTEGER NOT NULL,
   CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE purchase (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   buyer_id BIGINT,
   product_id BIGINT,
   count INTEGER NOT NULL,
   sum INTEGER NOT NULL,
   CONSTRAINT pk_order PRIMARY KEY (id)
);

ALTER TABLE purchase ADD CONSTRAINT FK_ORDER_ON_BUYER FOREIGN KEY (buyer_id) REFERENCES buyer (id);

ALTER TABLE purchase ADD CONSTRAINT FK_ORDER_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

INSERT INTO
  buyer
  (name)
VALUES
  ('Bob');

INSERT INTO
  buyer
  (name)
VALUES
  ('John');

INSERT INTO
  product
  (title, cost)
VALUES
  ('Red Apple', 80);

INSERT INTO
  product
  (title, cost)
VALUES
  ('Banana', 110);

INSERT INTO
  product
  (title, cost)
VALUES
  ('Orange', 115);

INSERT INTO
  product
  (title, cost)
VALUES
  ('Pineapple', 190);

INSERT INTO
  purchase
  (buyer_id, product_id, count, sum)
VALUES
  (1, 1, 1, 80);

INSERT INTO
  purchase
  (buyer_id, product_id, count, sum)
VALUES
  (2, 1, 2, 160);

INSERT INTO
  purchase
  (buyer_id, product_id, count, sum)
VALUES
  (1, 3, 3, 345);